# Используем Node.js как базовый образ
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы и устанавливаем зависимости
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Копируем весь проект
COPY . .

RUN npx prisma generate


# Открываем порт и запускаем сервер
EXPOSE 3000
CMD ["npm", "run", "start"]
